apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-container
          image: hunglq/product-app:e1083b83950196bde232965e1689bce8b8b7ff07
          ports:
            - containerPort: 8080
  strategy:
    type: Recreate