apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-container
          image: hunglq/product-app:9eb15ef75d2f264dcb5ed8ae442d2a78aa3f6b5c
          ports:
            - containerPort: 8080
  strategy:
    type: Recreate