apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-container
          image: hunglq/product-app:9d17609e12aa2df7776f003ec5db03ad76e34a25
          ports:
            - containerPort: 8080
  strategy:
    type: Recreate